// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ClockworkHighway.iOS
{
	public partial class ChargeViewController : UITableViewController
	{
		public ChargeViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
